[package]
name = "MAX31850K"
version = "0.1.0"
authors = ["Tyler Holmes <tylerdanielholmes@gmail.com>"]
edition = "2018"
categories = ["embedded", "no-std"]
keywords = ["rtfm", "embedded"]
license = "MIT OR Apache-2.0"


[dependencies]
